# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed567f32f99271979b02a71de63c46a745c1b2c0ee65748614c524e9187b1265d6d0d7d142907c9a2b5bf0bd1f18fa03c5ac173d968715a33ac1b1378e074c69

test:
  secret_key_base: 6447f3a1edb1c626fcd9a66dc900631061f9422ba296714fbe6fa9263d704a72e2de761101e5f2e6cdff71542fa14cd0fa778fd08cbdea2f16ac35783392c048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
